### ISSUE TITLE
Je comprends pas pourquoi vous faites cela.

### ISSUE THREAD

**Issue by TheForgeron** [LeProjetDeLaSemaine/Projet_ISN#1]
Je suis un compresé et je ne suis pas d'accord avec la decompression. veuillez refaire en mettant une decompression plus acceptable par l'ecologie et l'environnement. Cordiallement. 

PS. Nike sa. J'aime pas dutout.

**Comment by LeProjetDeLaSemaine** [comment]
On a scale from 1 to Snoop Dogg, how high were you when you wrote this shit ?

**Comment by TheForgeron** [comment]
Wizz Khalifa

**Comment by LeProjetDeLaSemaine** [comment]
Votre suggestion a bien été prise en compte, nous allons procéder à la fermeture de l'issue, merci de votre compréhension.
